### ISSUE TITLE
"Driver.SwitchTo().Window(windowHandle)" is not working for switching to a newly opened window in IE 11.

### ISSUE THREAD

**Issue by handakafunda** [light2yellow/ckb-next#18]
I need to switch between windows in my current project using selenium webdriver scripts. I am using the below code for switching.
1. navigated to the home page of application
2. String ParentWindow = Driver.Instance.CurrentWindowHandle; //stored the window handle of the application
3. clicked of the button and it opens a new window 
4. code to switch between window
IReadOnlyCollection<String> windowIterator = Driver.Instance.WindowHandles;
                Console.WriteLine("No of windows :  " + windowIterator.Count);
                foreach (String s in windowIterator)
                {
                    String windowHandle = s;
                    popup = Driver.Instance.SwitchTo().Window(windowHandle); //On this line it is showing No Window found for the second window handle in the above collection, it worked for the parent window.
                   // Console.WriteLine("Window Title : " + popup.Title);
                //    Console.WriteLine("Window Url : " + popup.Url);
                    if (popup.Title.Contains(title))
                    {
                        Console.WriteLine("Selected Window Title : " + popup.Title);
                        return popup;
                    }

                }

Can anyone help me with the issue it is very critical stopping me to progress in the script.
thanks in advance

- [ ] ``
Note:there is one difference in scenario i noticed while doing manually or using selenium webdriver ->1: main window has link and I click on that link 2: it opens up new iframe popup having preview button 3: I click on preview button and it opens a new window instead in selenium webdriver while on manual it opens in new tab in the same window

**Comment by light2yellow** [comment]
You have posted for the the wrong project, I suppose. Even if it is somehow related to ckb, its issues are [there](https://github.com/mattanger/ckb-next/issues), not here.
