### ISSUE TITLE
Resolve ckb-mviz license

### ISSUE THREAD

**Issue by light2yellow** [light2yellow/ckb-next#3]
- [x] Is ckb-mviz's license compatible to the one ckb-next is distributed under?
- [x] Do we need to ship its license with ckb-next's? If yes, how to inform a user about it? Probably change it's name?

**Comment by fleischie** [comment]
Disclaimer: I am no lawyer and have only a working knowledge of licensing.

- `ckb-next` is currently released under the GNU General Pulic License (GPL) v2.
- `ckb-mviz` is released under the BSD 3-clause license.

The latter license is compatible with the GPL.

We have to consider the architecture under which terms both programs are run:
`ckb-mviz` is a separate program, that is only instantiated and run via `ckb-next`.
<details>Thus it's awfully close to how linux handles this: The kernel is GPLv2 but hardware driver modules may be written closed source.</details>

**Comment by light2yellow** [comment]
@fleischie thanks for making it clear! I think we should describe this in the wiki eventually (because I never found any info about the contribution of animations) - that the licence should be compatible with GPL2 and so on.

**Comment by light2yellow** [comment]
Merging into #1.
